Remove redhat and try to install dolfinx from source

diff --git a/.github/workflows/test_workflow.yml b/.github/workflows/test_workflow.yml
--- a/.github/workflows/test_workflow.yml
+++ b/.github/workflows/test_workflow.yml
@@ -8,13 +8,51 @@ on:
         type: string
 
 jobs:
+
+  get_image_tag:
+    runs-on: ubuntu-latest
+    outputs:
+      image: ${{ steps.docker_tag.outputs.image }}
+    steps:
+
+      - name: Validate inputs
+        run: |
+          if [[ "${{ inputs.dolfinx_tag }}" != "stable" && "${{ inputs.dolfinx_tag }}" != "nightly"; then
+            echo "::error::Invalid DOLFINx enviroment: ${{ inputs.dolfinx_tag }}. Allowed values: stable, nightly"
+            exit 1
+          fi
+
+      - id: Nightly
+        if: (${{ inputs.dolfinx_tag }} == 'nightly')
+        run: |
+          echo "branch=main" >> $GITHUB_OUTPUT
+          echo "image=current" >> $GITHUB_OUTPUT
+
+      - id: Stable
+        if: (${{ inputs.dolfinx_tag }} == 'stable')
+        run: |
+          echo "branch=release" >> $GITHUB_OUTPUT
+          echo "image=stable" >> $GITHUB_OUTPUT
+
+
   test-code:
-    runs-on: ubuntu-24.04
-    # The container tag is now dynamic based on the input passed by the caller
-    container: ghcr.io/fenics/dolfinx/dolfinx:${{ inputs.dolfinx_tag }}
+    runs-on: ubuntu-latest
+    needs: get_image_tag
+
+    runs-on: ubuntu-latest
+    container: ghcr.io/fenics/dolfinx/dolfinx:${{ needs.get_image_tag.outputs.image }}
 
     steps:
       - uses: actions/checkout@v6
+
+      - name: Install DOLFINx
+        uses: jorgensd/actions/install-dolfinx@v0.4
+        with:
+          dolfinx: ${{ needs.get_image_tag.outputs.branch }}
+          basix: ${{ needs.get_image_tag.outputs.branch }}
+          ufl: ${{ needs.get_image_tag.outputs.branch }}
+          ffcx: ${{ needs.get_image_tag.outputs.branch }}
+          working-directory: ${{ env.working-directory}}
 
       - name: Update pip
         run: python3 -m pip install --upgrade pip
